[package]
name = "litex-fw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.68.1"

[dependencies]
riscv = "*"
riscv-rt = "*"
panic-halt = "*"
litex-hal = { path = "../deps/rust-litex-hal" }
litex-pac = { path = "../litex-pac", features = ["rt"] }
micromath = "2.0.0"
heapless = { version = "0.7.16", features = ["ufmt-impl"] }
ufmt = "0.2.0"
aligned-array = "1.0.1"
vexriscv = "0.0.3"
